os:
  - linux

git:
  depth: 1
  submodules: false

language: cpp

compiler:
  - clang
  - gcc

sudo: false

env:
  matrix:
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=C SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
    - PYTHON_VERSION=2.7 HPDDM_NUMBERING=F SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
    - PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO

matrix:
  exclude:
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=C SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
    - compiler: gcc
      env: PYTHON_VERSION=3.5 HPDDM_NUMBERING=F SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libmumps-dev
      - libarpack2-dev
      - libhypre-dev

cache:
  directories:
    - $HOME/.cache

before_cache:
  - find $HOME/miniconda/pkgs -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;

install:
  - mkdir -p $HOME/.cache/pkgs
  - if [ "$CXX" == "g++" ]; then export OMPI_CC="gcc-4.9"; export OMPI_CXX="g++-4.9"; else export OMPI_CC=$CC; export OMPI_CXX=$CXX; fi
  - if [ ! -f ${HOME}/.cache/miniconda${PYTHON_VERSION} ]; then
        if [ "$PYTHON_VERSION" == "2.7" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ${HOME}/.cache/miniconda${PYTHON_VERSION}.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/.cache/miniconda${PYTHON_VERSION}.sh;
        fi
    fi
  - bash ${HOME}/.cache/miniconda${PYTHON_VERSION}.sh -b -p ${HOME}/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - rm -rf ${HOME}/miniconda/pkgs && ln -s ${HOME}/.cache/pkgs ${HOME}/miniconda/pkgs
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON_VERSION nomkl numpy scipy
  - source activate test-environment
  - python -V
  - pip install --user mpi4py
  - cp Make.inc/Makefile.Travis-CI Makefile.inc
  - if [ "$FORCE_SINGLE" == "ON" ]; then export HPDDMFLAGS="-DFORCE_SINGLE"; fi
  - if [ "$FORCE_COMPLEX" == "ON" ]; then export HPDDMFLAGS="${HPDDMFLAGS} -DFORCE_COMPLEX"; fi
  - if [ "$CO" == "GENERAL_CO" ]; then export HPDDMFLAGS="${HPDDMFLAGS} -DGENERAL_CO"; fi
  - if [ "$HPDDM_NUMBERING" == "C" ]; then export HPDDMFLAGS="${HPDDMFLAGS} -DHPDDM_NUMBERING=\'C\'"; fi
  - if [ "$HPDDM_NUMBERING" == "F" ]; then export HPDDMFLAGS="${HPDDMFLAGS} -DHPDDM_NUMBERING=\'F\'"; fi
  - export CCFLAGS="-Wall -Wpedantic -Werror -Wno-sign-compare"
  - export CXXFLAGS="-Wall -Wpedantic -Werror -Wno-sign-compare"
  - if [ "$CXX" == "g++" ]; then export CCFLAGS="-Wno-literal-suffix -Wno-maybe-uninitialized ${CCFLAGS}"; export CXXFLAGS="-Wno-literal-suffix -Wno-maybe-uninitialized ${CXXFLAGS}"; fi
  - if [ "$PYTHON_VERSION" == "2.7" ]; then
      make all -j2;
    else
      export PYTHON_VERSION=3.5m; make python;
    fi

script:
  - if [ "$PYTHON_VERSION" == "2.7" ]; then
      make test_cpp test_c;
    fi
  - make test_python
  - if [ "$PYTHON_VERSION" == "2.7" ] && [ "$HPDDM_NUMBERING" == "F" ] && [ "$CO" == "GENERAL_CO" ] && [ "$FORCE_SINGLE" == "OFF" ]; then
      make test_bin/driver;
    fi

notifications:
  email:
    recipients:
      - hpddm@ljll.math.upmc.fr

branches:
  only:
    - master
