os:
  - linux

git:
  depth: 1
  submodules: false

language: cpp

compiler:
  - clang
  - gcc

sudo: false

env:
  - SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF
  - SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=OFF
  - SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=ON
  - SOLVER=MUMPS SUBSOLVER=MUMPS FORCE_SINGLE=ON FORCE_COMPLEX=ON
  - SOLVER=HYPRE SUBSOLVER=MUMPS FORCE_SINGLE=OFF FORCE_COMPLEX=OFF CO=GENERAL_CO

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - libmumps-dev
    - libarpack2-dev
    - libhypre-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc arpack cmake scalapack veclibfort; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install open-mpi --c++11; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install mumps; fi

install:
  - export OMPI_CXX=$CXX
  - if [ "$FORCE_SINGLE" == "ON" ]; then export CXX_FLAGS="-DFORCE_SINGLE"; fi
  - if [ "$FORCE_COMPLEX" == "ON" ]; then export CXX_FLAGS="${CXX_FLAGS} -DFORCE_COMPLEX"; fi
  - if [ "$CO" == "GENERAL_CO" ]; then export CXX_FLAGS="${CXX_FLAGS} -DGENERAL_CO"; fi
  - cd interface
  - if [ "$CXX" == "g++" ]; then export OMPI_CXX="g++-4.9"; export CXX_FLAGS="-Wno-literal-suffix ${CXX_FLAGS}"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mpicxx -std=c++11 schwarz.cpp -Wpedantic -Werror ${CXX_FLAGS} -I../src -I/usr/include -DD${SOLVER} -D${SUBSOLVER}SUB -L/usr/lib -lblas -llapack -lsmumps -ldmumps -lcmumps -lzmumps -lmumps_common -lpord -lHYPRE_IJ_mv -lHYPRE_krylov -lHYPRE_parcsr_ls -lscalapack-openmpi -larpack -lmpi_f77; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mpicxx -std=c++11 schwarz.cpp -Wpedantic -Werror ${CXX_FLAGS} -I../src -I/usr/local/include -DMUMPSSUB -DDMUMPS -L/usr/local/lib -larpack -lsmumps -ldmumps -lcmumps -lzmumps -lmumps_common -lpord -lscalapack -framework vecLib; fi

script:
  - mpirun -np 1 ./a.out -hpddm_verbosity
  - mpirun -np 1 ./a.out -symmetric_csr -hpddm_verbosity
  - mpirun -np 2 ./a.out -hpddm_tol=1e-6 -hpddm_schwarz_coarse_correction deflated -hpddm_geneo_nu=2 -hpddm_verbosity=2 -symmetric_csr
  - mpirun -np 4 ./a.out -hpddm_tol=1e-6 -hpddm_schwarz_coarse_correction deflated -hpddm_geneo_nu=10 -hpddm_verbosity=2 --hpddm_gmres_restart=15 -hpddm_max_it 80
  - mpirun -np 4 ./a.out -hpddm_tol=1e-6 -hpddm_schwarz_coarse_correction deflated -hpddm_geneo_nu=10 -hpddm_verbosity=2 -nonuniform -Nx 50 -Ny 50 -symmetric_csr
  - mpirun -np 8 ./a.out -hpddm_tol=1e-6 -hpddm_schwarz_coarse_correction balanced -hpddm_geneo_nu=0 -hpddm_verbosity=2 -Nx 40 -Ny 40 -hpddm_variant=right

notifications:
  email:
    recipients:
      - hpddm@ljll.math.upmc.fr

branches:
  only:
    - master
